[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.gd']

[phases.install]
cmds = ['echo "PHP 8.2 instalado com extensões necessárias"']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'
